spring.application.name=portal-app
server.port=19080
management.server.port=${MANAGEMENT_PORT:19081}
management.endpoints.web.exposure.include=health,metrics,prometheus
management.metrics.tags.application=${spring.application.name}

# =============================================================================
# Nacos Config
# =============================================================================
spring.cloud.nacos.config.server-addr=${NACOS_SERVER_ADDR:104.223.27.218:8848}
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:dev}
spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.config.password=${NACOS_PASSWORD:qw123456}

# 节点 ID
node.id=${PORTAL_NODE_ID:portal-01}

spring.config.import=\
  nacos:global.common-infra.properties?group=GLOBAL_COMMON&refresh=true,\
  nacos:global.common-logging.properties?group=GLOBAL_COMMON&refresh=true

# =============================================================================
# 服务私有配置
# =============================================================================

# 通用节点发现
node.discovery.node-id=${node.id}
node.discovery.node-type=LOGIN_NODE
node.discovery.port=${server.port}
node.discovery.routing-key-type=NONE
